# Starter pipeline
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 
    jobs:
      - job: "build"
        steps:
          - script: dotnet build 'Project 0/Project 0.sln'
      - job: "test"
        dependsOn: "build"
        steps:
          - script: dotnet test 'Xunittest/Xunittest.csproj'
      - job: "Prepare"
        steps:
          - script: dotnet build 'Project 0/Project 0.sln'
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'AzureDevOpsSonarCloud'
              organization: 'asrailuna'
              scannerMode: 'Other'
          - task: SonarCloudAnalyze@1
        

              


